name: 'Build Dist'

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

env:
  BOT_TOKEN: ${{ secrets.BOT_TOKEN }}

jobs:
  dist:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
      - name: Checkout
        uses: actions/checkout@v4
      - run: chmod +x .github/workflows/dist.sh && bash .github/workflows/dist.sh
